[project]
dependencies = []
description = "A Copier template for Python with Mise"
name = "python-template"
readme = "README.md"
requires-python = ">=3.12"
version = "0.2.0"

[dependency-groups]
dev = ["copier>=9.9.1", "pytest>=8.4.1", "ruff>=0.12.10"]
